/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2junio;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author LUIS QUIÑONEZ
 */
public class Ventana extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Ventana
     */
    private AnalisisLexico analisis_lexico;//debug
    private AnalisisSintactico analisis_sintactico;//debug
    private List<JTextArea> lista_texto;
    private List<JPanel> lista_pestanya;
    private List<JScrollPane> lista_jscroll;
    private int seleccion;
    private List<Pestanya> lista_tab;//nuevo
    
    
    public Ventana() {
        super("AGE");//titulo de la aplicacion
        initComponents();
        //this.analisis_lexico = new AnalisisLexico();//debug
        lista_texto = new ArrayList<>();
        lista_pestanya = new ArrayList<>();
        lista_jscroll = new ArrayList<>();
        lista_tab = new ArrayList<>();
        seleccion = -1;
        //this.analisis_sintactico = new AnalisisSintactico();
        anyadirAcciones();
    }

    
    private void anyadirAcciones(){
        this.iniciar_Analisis.addActionListener(this);
        this.abrir_archivo.addActionListener(this);
        this.menu_nuevo.addActionListener(this);
        this.boton_graficar.addActionListener(this);
        this.guardar_archivo.addActionListener(this);
        this.reporte_tokens.addActionListener(this);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_edicion = new javax.swing.JPanel();
        panel_pestanya = new javax.swing.JTabbedPane();
        panel_opciones = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_componentes = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista_producciones = new javax.swing.JList<>();
        boton_graficar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        abrir_archivo = new javax.swing.JMenuItem();
        guardar_archivo = new javax.swing.JMenuItem();
        menu_nuevo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        iniciar_Analisis = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        reporte_tokens = new javax.swing.JMenuItem();
        reporte_errores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_edicion.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_edicionLayout = new javax.swing.GroupLayout(panel_edicion);
        panel_edicion.setLayout(panel_edicionLayout);
        panel_edicionLayout.setHorizontalGroup(
            panel_edicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_pestanya, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );
        panel_edicionLayout.setVerticalGroup(
            panel_edicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_edicionLayout.createSequentialGroup()
                .addComponent(panel_pestanya, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        panel_opciones.setBackground(new java.awt.Color(204, 204, 204));

        jScrollPane2.setViewportView(lista_componentes);

        jScrollPane3.setViewportView(lista_producciones);

        boton_graficar.setBackground(new java.awt.Color(255, 255, 255));
        boton_graficar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        boton_graficar.setText("Graficar");
        boton_graficar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Componentes Lexicos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Producciones");

        javax.swing.GroupLayout panel_opcionesLayout = new javax.swing.GroupLayout(panel_opciones);
        panel_opciones.setLayout(panel_opcionesLayout);
        panel_opcionesLayout.setHorizontalGroup(
            panel_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_opcionesLayout.createSequentialGroup()
                .addGroup(panel_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(boton_graficar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_opcionesLayout.setVerticalGroup(
            panel_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_opcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boton_graficar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        abrir_archivo.setText("Abrir");
        jMenu1.add(abrir_archivo);

        guardar_archivo.setText("Guardar");
        guardar_archivo.setEnabled(false);
        jMenu1.add(guardar_archivo);

        menu_nuevo.setText("Nuevo");
        jMenu1.add(menu_nuevo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Herramientas");

        iniciar_Analisis.setText("Analizar");
        jMenu2.add(iniciar_Analisis);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reportes");

        reporte_tokens.setText("Tokens");
        jMenu3.add(reporte_tokens);

        reporte_errores.setText("Errores");
        jMenu3.add(reporte_errores);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_edicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_opciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir_archivo;
    private javax.swing.JButton boton_graficar;
    private javax.swing.JMenuItem guardar_archivo;
    private javax.swing.JMenuItem iniciar_Analisis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lista_componentes;
    private javax.swing.JList<String> lista_producciones;
    private javax.swing.JMenuItem menu_nuevo;
    private javax.swing.JPanel panel_edicion;
    private javax.swing.JPanel panel_opciones;
    private javax.swing.JTabbedPane panel_pestanya;
    private javax.swing.JMenuItem reporte_errores;
    private javax.swing.JMenuItem reporte_tokens;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==this.iniciar_Analisis){
            iniciarAnalisis();
        }
        else if(e.getSource()==this.abrir_archivo){
            abrir();
        }
        else if(e.getSource()==this.menu_nuevo){
            nuevo();
        }
        else if(e.getSource()==this.guardar_archivo){
            guardar();
        }
        
    }
    
    
    private void abrir(){
        Archivo archivo = new Archivo();//nuevo
        String texto = archivo.abrir();
        seleccion++;//aumento el indice de la seleccion empieza en -1 asi que se convierte en 0 la primera vez
        
        Pestanya pestanya = new Pestanya();
        pestanya.getText_area().setText(texto);
        pestanya.setRuta(archivo.getRuta());
        lista_tab.add(pestanya);
        panel_pestanya.add(lista_tab.get(seleccion).getPanel());
        panel_pestanya.setSelectedIndex(seleccion);
        
        
        if(!this.guardar_archivo.isEnabled())//nuevo
            guardar_archivo.setEnabled(true);
            
            /*
            lista_texto.add(new JTextArea());//creo un nuevo campo de texto y lo meto en una lista
            lista_texto.get(seleccion).setText(texto);//le agrego el texto del documento al cuadro de texto
            
            lista_jscroll.add(new JScrollPane(lista_texto.get(seleccion)));//creo un nuevo jscrollpane y le agrego el jtextarea
            lista_jscroll.get(seleccion).setBounds(0,0,378,449);//cambio el tamaño y ubicacion del jscrollpane
            
            lista_pestanya.add(new JPanel());//creo una nueva pestaña y la meto en una lista
            lista_pestanya.get(seleccion).setLayout(null);//elimino layout para que funcione el jscrollpane
            lista_pestanya.get(seleccion).add(lista_jscroll.get(seleccion));//coloco el cuadro de texto en el panel
            
            panel_pestanya.add(lista_pestanya.get(seleccion));//agrego la nueva pestaña
            panel_pestanya.setSelectedIndex(seleccion);//pongo focus en la pestaña
            */
    }
    
    private void nuevo(){
        seleccion++;
        lista_tab.add(new Pestanya());
        panel_pestanya.add(lista_tab.get(seleccion).getPanel());
        panel_pestanya.setSelectedIndex(seleccion);
        if(!this.guardar_archivo.isEnabled())//nuevo
            guardar_archivo.setEnabled(true);
    }
    
    private void guardar(){ 
        seleccion=this.panel_pestanya.getSelectedIndex();
        String[] salida = lista_tab.get(seleccion).getText_area().getText().split("\n");//lista_texto.get(seleccion).getText().split("\n");
        if(lista_tab.get(seleccion).getRuta().isEmpty()){
            lista_tab.get(seleccion).setRuta(new Archivo().guardar(salida));
        }else{
            JOptionPane.showMessageDialog(null,new Archivo().guardarComo(lista_tab.get(seleccion).getRuta(), salida));
        }
    }
    
    private void iniciarAnalisis(){
            //String texto = lista_texto.get(panel_pestanya.getSelectedIndex()).getText();//cuidado
            String  texto = lista_tab.get(panel_pestanya.getSelectedIndex()).getText_area().getText();
            this.analisis_lexico=new AnalisisLexico();
            this.analisis_lexico.analizar(texto);
            this.analisis_sintactico = new AnalisisSintactico(this.analisis_lexico);
            /*for(Token token:this.analisis_lexico.getToken()){
                System.out.println(token.getNumero()+".-"+token.getLexema()+" fila: "+token.getLinea()+" columna: "+token.getColumna() +" ID: "+token.getID());
            }*/
            analisis_sintactico.analizar();
            DefaultListModel modelo = new DefaultListModel();
            for(String componente:analisis_sintactico.getComponente()){
                modelo.addElement(componente);
            }
            this.lista_componentes.setModel(modelo);
            
            DefaultListModel modelo2 = new DefaultListModel();//nuevo
            for(String PR:analisis_sintactico.getPR()){//nuevo
                modelo2.addElement(PR);
            }
            this.lista_producciones.setModel(modelo2);//nuevo
            
            for(String produccion: analisis_sintactico.getProduccion()){//debug
                System.out.println(produccion);
            }        
    }
}
